language: bash

services:
  - docker

env:
  global:
    - ALI_REGISTRY=registry.us-west-1.aliyuncs.com/my-k8s-gcr-io/google_containers.kube-apiserver

before_script:
  - 

script:
  - echo "start pull and retag and push"
  - |
    for image in $(cat img-list.txt)
    do
    	image_name=${image##*/}
    	docker pull $image
        echo $ALI_REGISTRY
        docker tag $image $ALI_REGISTRY/$image_name
        
    	# push到阿里云仓库
    	docker push $ALI_REGISTRY/$image_name
    done
